[versions]
kotlin = "2.3.0"
fabric-loom = "1.10-SNAPSHOT"
spotless = "8.1.0"
lombok = "9.1.0"

minecraft = "1.18.2"
fabric-loader = "0.18.1"
fabric-api = "0.77.0+1.18.2"
fabric-kotlin = "1.13.8+kotlin.2.3.0"

reachentityattributes = "2.2.0"
quack = "0.4.10.117"
portinglib = "1.2.1584-beta+1.18.2"
spotbugs-annotations = "4.9.8"

modmenu = "3.2.5"
lazydfu="0.1.2"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }

reachentityattributes = { module = "com.jamieswhiteshirt:reach-entity-attributes", version.ref = "reachentityattributes" }
quack = { module = "net.covers1624:Quack", version.ref = "quack" }
portinglib = { module = "io.github.fabricators_of_create:Porting-Lib", version.ref = "portinglib" }
spotbugs-annotations = { module = "com.github.spotbugs:spotbugs-annotations", version.ref = "spotbugs-annotations" }

modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
lazydfu = { module = "maven.modrinth:lazydfu", version.ref = "lazydfu" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
